before:
  hooks:
    - go mod tidy
builds:
  - id: open-esa
    main: ./cmd/open-esa
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
archives:
  - files:
      - README.md
      - open-esa.toml.sample
