before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/openesa
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
archives:
  - files:
      - README.md
      - openesa.toml.sample
