#!/bin/bash
set -e

envsubst '
  $OPENESA_ADDR
  $OPENESA_PORT
  $OPENESA_TAEM
  $OPENESA_PER_PAGE
  $OPENESA_SESSION_SECRET
  $OPENESA_COOKIE_SECURE
  $OPENESA_OAUTH2_CLIENT_ID
  $OPENESA_OAUTH2_CLIENT_SECRET
  $OPENESA_OAUTH2_REDIRECT_HOST
' < /openesa.toml.template > /openesa.toml

exec /openesa
